### ISSUE TITLE
Can FileSDK support Android?

### ISSUE THREAD

**Issue by Monutchuan** [IncantaGames/unreal-bp-file-sdk#5]

**Comment by mikeseese** [comment]
We haven't tested Android, and it's unlikely we'll officially support it anytime soon. You can test it out by adding `"Android"` to this array: https://github.com/IncantaGames/unreal-bp-file-sdk/blob/master/FileSDK.uplugin#L23

It should go without saying, but you'll need to install the plugin as a project plugin to make that adjustment: https://wiki.incanta.games/en/plugins/install-as-project-plugin

**Comment by Monutchuan** [comment]
Okay, hope that an official Android version will be released eventually, and I hope that the old UE4 version of the plug-in will also be updated.

**Comment by mikeseese** [comment]
The old UE4 version of the plugin will not be updated. We only support the last 3 versions of Unreal (so currently 5.1, 5.2, and 5.3). It's possible that the latest `master` branch does support UE4 if you follow the guide I linked in the previous comment. Lastly, I'm happy to review any pull requests if you find anything missing (e.g. if you find a bug that effects Android or UE4 that can cohesively be merged in). In the meantime, neither of these are on our roadmap so I'm going to close this issue. Best of luck!
