### ISSUE TITLE
Convert Texture2D to Byte array

### ISSUE THREAD

**Issue by charan-vendra** [IncantaGames/unreal-bp-file-sdk#7]

**Comment by mikeseese** [comment]
@charan-vendra there's a BP node built into UE that will do the conversion for you:
![image](https://github.com/user-attachments/assets/3287f61e-cb0d-4751-9e1f-d5b897b4a410)

**Comment by charan-vendra** [comment]
@mikeseese is it available in 5.3, because I couldn't find it, also do I need to enable any plugin?

**Comment by mikeseese** [comment]
@charan-vendra I'm not sure, I was in 5.4 when I found this node. I'm now AFK. I googled this for you and found someone recommending this free plugin that might help you out: https://www.fab.com/listings/0aadd41b-c02d-4f63-9009-bffad0070ebc

Regardless, I don't plan to add support for this to the plugin as this plugin doesn't deal with file formats or parsing. It's up to you to handle that. Best of luck!

**Comment by charan-vendra** [comment]
Hi @mikeseese Thank you so much for your response, I am just trying to get this done myself, I don't want to bother you too much.

I tried to find the node in 5.4 too with no luck... I also checked out the plugin, but couldn't find a node that can help me convert from Texture2D to bytes.

I understand if you can't help anymore, regardless thanks for trying to help.

**Comment by charan-vendra** [comment]
> @charan-vendra there's a BP node built into UE that will do the conversion for you: ![image](https://private-user-images.githubusercontent.com/549323/388629820-3287f61e-cb0d-4751-9e1f-d5b897b4a410.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzE0MTQsIm5iZiI6MTczMjM3MTExNCwicGF0aCI6Ii81NDkzMjMvMzg4NjI5ODIwLTMyODdmNjFlLWNiMGQtNDc1MS05ZTFmLWQ1Yjg5N2I0YTQxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QxNDExNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmQ0ZWEwODkxN2U5YTVhZDUyMzIyNjg5NDhlYTE0N2VlN2IzMTZkMDkwOTVkYWI0ZGMyYzU0ZmYzNzhkNTdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bc4GQ6d5glFdmZ_vWGoOdGxPtVT5XuNuqiKnurmRJe4)

@mikeseese  It would really help me even if you just told me how you found this node, because that is the exact node I am looking for 🥺

**Comment by mikeseese** [comment]
I just went into the event graph, right clicked, and typed texture2d bytes and eventually found that. Typing "to bytes" should show this node. Perhaps there's a plugin installed in 5.4 by default or one of my other plugins is enabling it. Check the plugins for blueprint utilities or something like that.

**Comment by charan-vendra** [comment]
Can you send your ini file that contains list of plugins?

**Comment by mikeseese** [comment]
I'm AFK, sorry. You're on your own from here.
